packages/pandora/src/application/ApplicationHandler.ts
packages/pandora/src/application/ProcessBootstrap.ts
packages/pandora/src/daemon/Daemon.ts
packages/pandora/src/daemon/SpawnWrapperUtils.ts
packages/pandora/src/daemon/spawnWrapper.ts
packages/pandora/src/universal/LoggerBroker.ts

fix issues about spawn-wrap within unit test, and restrict it only works on fork mode

spawn-wrap went wrong

---

packages/pandora/cli/ps.js
packages/pandora/package.json

bebore:
after:
The `pandora ps` performance gets a 125x boost! (results may vary depending on different situations  )

Greatly improve `pandora ps` performance

---

packages/metrics/src/endpoint/CacheDuplexEndPoint.ts
packages/metrics/src/endpoint/impl/TraceEndPoint.ts
packages/metrics/src/reporter/TraceReporter.ts
packages/metrics/src/util/CommonCache.ts
packages/metrics/test/unit/util/LogCache.test.ts

fix: improve common cache

---

packages/hub/src/Facade.ts
packages/pandora/src/Facade.ts
packages/pandora/src/application/WorkerContextAccessor.ts
packages/pandora/src/index.ts
packages/pandora/src/service/ServiceContextAccessor.ts

配对全局的 getProxy() ... 之前忘了加
#57

feat: expose publishObject()

---

packages/hook/src/patch/http.ts
packages/hook/src/patch/urllib.ts

+ 为 urllib 和 http hook 添加 beforeFinish 方法

fix: add beforeFinish to urllib and http hook

---

packages/hook/src/patch/urllib.ts

fix: add after finish to urllib hook

---

packages/metrics/src/trace/TraceManager.ts
packages/metrics/src/trace/Tracer.ts

fix: catch error when ns missing

fix: catch error when ns missing

---

packages/dollar/package.json
packages/env/package.json
packages/hook/package.json
packages/hook/test/fixtures/egg-logger/index.ts
packages/hook/test/fixtures/global/index.ts
packages/hook/test/fixtures/http/index.ts
packages/hook/test/fixtures/integrate/index.ts
packages/hook/test/fixtures/urllib/index.ts
packages/hub/package.json
packages/hub/src/hub/HubClient.ts
packages/messenger/d.ts/sdk-base.d.ts
packages/messenger/package.json
packages/messenger/src/client.ts
packages/messenger/src/index.ts
packages/messenger/test/client.test.ts
packages/metrics/package.json
packages/metrics/src/trace/TraceManager.ts
packages/metrics/src/trace/cls.ts
packages/metrics/src/util/MessengerUtil.ts
packages/pandora/package.json
packages/pandora/src/application/ProcessBootstrap.ts
packages/pandora/src/application/spawnWrapper.ts
packages/pandora/src/daemon/Daemon.ts
packages/pandora/test/application/ApplicationHandler.test.ts
packages/pandora/test/bug/unref.test.ts
packages/pandora/test/fixtures/project/short_exec/app.js
packages/pandora/test/fixtures/project/short_exec/procfile.js
packages/pandora/test/fixtures/project/short_exec/x.js
packages/service-logger/package.json
packages/service-logger/src/LoggerManager.ts

fix: #72 #73

---

packages/hook/src/index.ts
packages/hook/src/patch/shimmers/mysql/Shimmer.ts

+ 导出 http client shimmer，以便复用
+ 调整 mysql 类型声明

feat: export http client shimmer

---

packages/hook/src/patch/shimmers/http-client/Shimmer.ts
packages/hook/src/patch/shimmers/mysql/Shimmer.ts
packages/hook/test/fixtures/mysql2-promise/index.ts
packages/hook/test/fixtures/mysql2-promise/package.json
packages/hook/test/index.test.ts

+ 抽象 http client 和 mysql 的 hook 方法，以便内部继承修改
+ 添加 mysql2 promise 测试
+ 修复 mysql callback 队列后丢失上下文的问题

fix: abstract hook method

---

packages/hook/src/index.ts
packages/hook/src/patch/shimmers/http-client/Shimmer.ts

fix: export hook constants

---

packages/metrics/src/collect/MetricsCollector.ts
packages/metrics/src/common/reservoir/ExponentiallyDecayingReservoir.ts
packages/metrics/src/endpoint/impl/MetricsEndPoint.ts
packages/metrics/src/reporter/FileMetricsManagerReporter.ts
packages/metrics/test/unit/collector/MetricsCollector.test.ts

test: add lots of metricsCollector test

---

packages/metrics/src/collect/MetricObject.ts
packages/metrics/test/unit/collector/MetricsCollector.test.ts

Fix metric object

---

packages/metrics/src/common/metrics/Meter.ts
packages/metrics/src/common/util/EWMA.ts
packages/metrics/test/unit/common/metrics/Meter.test.ts
packages/metrics/test/unit/common/util/BinaryHeap.test.ts
packages/metrics/test/unit/common/util/EWMA.test.ts

feat: add meter test and compare results with java code

---

packages/metrics/src/metrics/os/CpuUsageGaugeSet.ts
packages/metrics/src/metrics/os/NetTrafficGaugeSet.ts

fix: can't show cpu value  in metrics list

---

packages/metrics/src/MetricsClient.ts
packages/metrics/src/MetricsServerManager.ts
packages/metrics/src/common/MetricsRegistry.ts
packages/metrics/src/domain.ts
packages/metrics/test/unit/common/metrics/Timer.test.ts
packages/pandora/src/daemon/Daemon.ts
packages/pandora/src/default.ts
packages/pandora/src/domain.ts
packages/pandora/src/monitor/Monitor.ts
packages/pandora/test/monitor/Monitor.test.ts

处理几个问题
1、进程重启，metrics 没有清理 #39 
2、让 monitor 可配置，有覆盖的需求

clean metrics when process died

---

packages/metrics/src/collect/CompactMetricsCollector.ts
packages/metrics/src/collect/NormalMetricsCollector.ts
packages/metrics/src/endpoint/impl/MetricsEndPoint.ts
packages/metrics/src/reporter/FileMetricsManagerReporter.ts
packages/metrics/src/rest/ProcessResource.ts
packages/metrics/test/unit/collector/MetricsCollector.test.ts

feat: optimize collector get gauges value

---

packages/hook/src/patch/shimmers/mysql/Shimmer.ts

fix: fix mysql hook

---

packages/metrics/src/metrics/os/NetTrafficGaugeSet.ts

fix: fix net traffic metrics get empty value

---

docs/source/en/process/ipc_hub.md
docs/source/languages/en.yml

translate: IPC-Hub

---

docs/source/en/base/debug.md
docs/source/en/process/process_std.md

+ base/debug 英文文档
+ process/process_std 英文文档

feat: add base debug and custom process english version docs

---

packages/hook/src/patch/EggLogger.ts
packages/hook/src/patch/HttpServer.ts
packages/hook/test/fixtures/egg-logger/index.ts
packages/metrics/src/trace/Tracer.ts
packages/metrics/src/util/TraceUtil.ts

+ 调整 egg-logger 实现
+ 增加 tracer.named 方法，可以快速命名及重命名

feat: improve egg-logger hook

---

packages/metrics/src/client/CachedMetricSet.ts
packages/metrics/src/metrics/os/NetTrafficGaugeSet.ts
packages/metrics/src/metrics/os/TcpGaugeSet.ts

fix: fix net traffic and tcp data

---

packages/metrics/src/client/CachedMetricSet.ts
packages/metrics/src/metrics/os/NetTrafficGaugeSet.ts
packages/metrics/src/metrics/os/TcpGaugeSet.ts
packages/metrics/src/util/Mutex.ts

feat: use mutex replace event

---

packages/hook/src/patch/Redis.ts
packages/hook/test/fixtures/redis-cluster/index.ts

+ 增加 finish 参数，便于之后获取请求和响应详情
+ 修复 redis-cluster 测试偶尔失败问题。

fix: add more data to redis and fix cluster failure

---

packages/hook/src/patch/shimmers/http-client/Shimmer.ts

fix: fix http method empty

---

packages/pandora/bin/pandora
packages/pandora/package.json

fix: node version

---

packages/hook/package.json
packages/hook/src/index.ts
packages/hook/src/patch/Mongodb.ts
packages/hook/src/patch/shimmers/mongodb/Constants.ts
packages/hook/src/patch/shimmers/mongodb/Shimmer.ts
packages/hook/src/utils/Database.ts
packages/hook/test/fixtures/mongodb/index.ts
packages/hook/test/fixtures/mongodb/package.json
packages/hook/test/index.test.ts
packages/metrics/src/trace/PandoraSpan.ts
packages/pandora/src/default.ts

feat: add mongodb hook

---

examples/service-and-ipc/ServiceA.js
examples/service-and-ipc/ServiceB.js

fix: ipc service export

---

packages/hook/src/patch/HttpClient.ts
packages/hook/src/patch/HttpServer.ts
packages/hook/src/patch/shimmers/mysql/Shimmer.ts
packages/hook/test/fixtures/http/index.ts
packages/metrics/src/trace/Patcher.ts

feat: hook plugins

---

packages/hook/src/patch/HttpServer.ts
packages/metrics/src/trace/TraceManager.ts
packages/pandora/README.md

fix: fix hook plugins

---

packages/metrics/src/trace/Patcher.ts

fix: update hook plugins load method

---

README.md
package.json
packages/pandora/README.md

doc: upgrade node version

---

packages/metrics/src/MetricsActuatorManager.ts
packages/pandora/src/daemon/DaemonIntrospection.ts
packages/pandora/src/universal/GlobalConfigProcessor.ts

fix: global config multiple loaded when pandora init

---

packages/hook/package.json
packages/hook/src/patch/Mongodb.ts
packages/metrics/src/index.ts

+ 导出 trace 相关模块
+ 修正 mongodb 适配版本

feat: export trace module and fix mongodb version

---

packages/hook/test/fixtures/http-record-get/index.ts
packages/hook/test/fixtures/http-record-post/index.ts
packages/hook/test/fixtures/http-record-query-and-data/index.ts
packages/metrics/src/util/TraceUtil.ts

+ stringify all log filed value

fix: stringify log field value

---

packages/hook/src/patch/shimmers/mysql/Shimmer.ts

+ 捕获 sql parse error
+ 在出错时给出提示，收集错误的 sql

fix: catch mysql parse error and add warn

---

packages/hook/src/patch/EggLogger.ts
packages/hook/src/patch/Global.ts

+ remove next tick in egg-logger and global hook

fix: remove next tick in error

---

packages/hook/package.json
packages/hook/src/patch/Log4js.ts
packages/hook/test/fixtures/log4js/index.ts
packages/hook/test/fixtures/log4js/package.json
packages/hook/test/index.test.ts

feat: collect log4js log

---

packages/metrics/src/index.ts
packages/pandora/src/default.ts

feat: enable trace reporter

---

packages/hook/package.json
packages/hook/src/patch/EggLogger.ts

feat: support egg-logger 2.x

---

packages/hook/src/patch/HttpServer.ts
packages/hub/test/hub/Hub.test.ts

feat: support custom http trace name

---

packages/component-auto-patching/src/Patcher.ts
packages/component-auto-patching/src/patchers/wrappers/http-client/HttpClientWrapper.ts
packages/component-auto-patching/src/patchers/wrappers/mysql/MySQLWrapper.ts
packages/component-auto-patching/test/fixtures/integration.ts
packages/component-auto-patching/test/integration.test.ts

+ 使用 httpServer 作为统一的 parent 节点。如果记录父子关系，难以确认子节点完成与否和父节点完成与否的关系，时间包含难以计算。

feat: use httpServer as parent and test

---

packages/component-auto-patching/src/patchers/MySQLPatcher.ts
packages/component-auto-patching/test/MySQLPatcher.test.ts

+ udpate mysql patcher transformSql

fix: update mysql patcher tracing method

---

packages/component-auto-patching/src/patchers/HttpClientPatcher.ts
packages/component-auto-patching/src/patchers/HttpServerPatcher.ts
packages/component-auto-patching/src/patchers/MySQLPatcher.ts
packages/component-auto-patching/test/MySQLPatcher.test.ts
packages/component-auto-patching/test/fixtures/http-server/HttpServerTraceName.ts

fix: fix span tag name

---

packages/component-auto-patching/src/constants.ts
packages/component-auto-patching/src/domain.ts
packages/component-auto-patching/src/patchers/HttpClientPatcher.ts
packages/component-auto-patching/src/patchers/HttpServerPatcher.ts
packages/component-auto-patching/src/patchers/MySQLPatcher.ts
packages/component-auto-patching/src/utils.ts
packages/component-auto-patching/test/HttpClientPatcher.test.ts
packages/component-auto-patching/test/fixtures/http-client/HttpClientFullUrl.ts
packages/component-auto-patching/test/fixtures/http-server/HttpServerTraceName.ts
packages/component-auto-patching/test/utils.test.ts

+ change http span tag
+ add http client fullUrl record

fix: fix http url tag

---

packages/component-auto-patching/src/patchers/HttpClientPatcher.ts

fix: fix http client size

---

packages/tracer/src/PandoraSpan.ts
packages/tracer/src/PandoraSpanContext.ts
packages/tracer/src/utils.ts

+ PandoraSpan 和 PandoraSpanContext 增加 toJSON 方法

feat: add toJSON to span and context

---

packages/component-auto-patching/src/ComponentAutoPatching.ts

feat: enable global patcher all

---

packages/component-file-logger-service/test/FileLoggerManager.test.ts
packages/component-sandbox-file-reporter/src/SandboxErrorLogFileReporter.ts
packages/component-sandbox-file-reporter/src/SandboxMetricsFileReporter.ts
packages/component-sandbox-file-reporter/src/SandboxTraceFileReporter.ts
packages/component-sandbox-file-reporter/test/SandboxErrorLogFileReporter.test.ts

1. 解决 ErrorLogFileReporter 的 level 配置不生效问题
2. 移除没啥用的 seed 字段

fix: reporter level config not work

---

.eslintrc.json
package.json
packages/component-file-logger-service/package.json
packages/component-file-logger-service/src/ComponentFileLoggerService.ts
packages/component-file-logger-service/src/FileLoggerEndPoint.ts
packages/component-file-logger-service/src/FileLoggerRotator.ts
packages/component-file-logger-service/src/types.ts
packages/component-file-logger-service/test/ComponentFileLoggerService.test.ts
packages/component-reporter-arms/src/ArmsIndicator.ts
packages/hub/src/config-manager/ConfigClient.ts
packages/messenger/src/client.ts
packages/messenger/src/sdk-base.d.ts

+ register file to rotate by api and endpoint
+ support rotate method: size truncate, like 'cat /dev/null > file'

Feat: size truncate

---

packages/component-file-logger-service/src/ComponentFileLoggerService.ts
packages/component-file-logger-service/src/FileLoggerEndPoint.ts
packages/component-file-logger-service/src/FileLoggerRotator.ts
packages/component-file-logger-service/test/ComponentFileLoggerService.test.ts

+ add remove log rotator strategy by component api

feat: add remove logrotator strategy api

---

packages/component-file-logger-service/src/ComponentFileLoggerService.ts
packages/component-file-logger-service/src/FileLoggerEndPoint.ts
packages/component-file-logger-service/src/FileLoggerRotator.ts
packages/component-file-logger-service/src/types.ts
packages/component-file-logger-service/test/ComponentFileLoggerService.test.ts

+ rotator strategy option - ignoreHeartbeat

feat: rotator strategy option - ignoreHeartbeat
